package pos;


/**
* pos/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Domingo, 19 de Junho de 2016 23h06min32s BRT
*/

public interface Message extends MessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Message
