package pos;

/**
* pos/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Domingo, 19 de Junho de 2016 23h06min32s BRT
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public pos.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (pos.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pos.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pos.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pos.MessageHelper.type ();
  }

}
