package pos;


/**
* pos/MessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Message.idl
* Domingo, 19 de Junho de 2016 23h06min32s BRT
*/

public interface MessageOperations 
{
  String hello ();
} // interface MessageOperations
